#!/bin/bash
# Copyright 2023 Nicolas Paul. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

options=(
	style=round
	width=6.0
	hidpi=on
	active_color=0xff00ff00
	inactive_color=0xff414550
)

borders "${options[@]}"
