# Copyright 2024 Nicolas Paul.  All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the COPYRIGHT file.

#                         █████
#                       ███░░░███
#  ████████    ██████  ███   ░░███     Nicolas Paul
# ░░███░░███  ███░░███░███    ░███
#  ░███ ░███ ░███ ░░░ ░███    ░███     n@nc0.fr
#  ░███ ░███ ░███  ███░░███   ███      https://x.com/nc0_r
#  ████ █████░░██████  ░░░█████░
# ░░░░ ░░░░░  ░░░░░░     ░░░░░░
#
# Nicolas Paul's AeroSpace configuration.
#
# Navigation is done using POSIX Vi movement keys (hjkl).
# Also, the prefix key is not Alt (Option) as I use it on Apple's International
# Keyboard to write non-English characters.

start-at-login = true

enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

gaps.inner.horizontal = 8
gaps.inner.vertical   = 4
gaps.outer.left       = 16
gaps.outer.bottom     = 8
gaps.outer.top        = 8
gaps.outer.right      = 16

[mode.main.binding]
ctrl-enter = 'exec-and-forget open -n /Applications/WezTerm.app'

# POSIX Vi movement keys
ctrl-h = 'focus left'
ctrl-j = 'focus down'
ctrl-k = 'focus up'
ctrl-l = 'focus right'

ctrl-shift-h = 'move-through left'
ctrl-shift-j = 'move-through down'
ctrl-shift-k = 'move-through up'
ctrl-shift-l = 'move-through right'

ctrl-shift-space = 'layout floating tiling' # 'floating toggle' in i3

ctrl-1 = 'workspace 0'
ctrl-2 = 'workspace 1'
ctrl-3 = 'workspace 2'
ctrl-4 = 'workspace 3'
ctrl-5 = 'workspace 4'
ctrl-6 = 'workspace 5'
ctrl-7 = 'workspace 6'
ctrl-8 = 'workspace 7'
ctrl-9 = 'workspace 8'
ctrl-0 = 'workspace 9'

ctrl-tab       = 'workspace next'
ctrl-shift-tab = 'workspace prev'

ctrl-shift-c = 'reload-config'

ctrl-w = 'mode window'

[mode.window.binding]
h = 'resize width +10'
j = 'resize height -10'
k = 'resize height +10'
l = 'resize width -10'

minus = 'resize smart -20'
equal = 'resize smart +20'
enter = 'flatten-workspace-tree'

v = 'split horizontal'
s = 'split vertical'
z = 'fullscreen'
d = 'close'
x = 'close-all-windows-but-current'

1 = 'move-node-to-workspace 0'
2 = 'move-node-to-workspace 1'
3 = 'move-node-to-workspace 2'
4 = 'move-node-to-workspace 3'
5 = 'move-node-to-workspace 4'
6 = 'move-node-to-workspace 5'
7 = 'move-node-to-workspace 6'
8 = 'move-node-to-workspace 7'
9 = 'move-node-to-workspace 8'
0 = 'move-node-to-workspace 9'

esc = 'mode main'
