# Copyright 2024 Nicolas Paul.  All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the COPYRIGHT file.

column_width = 100
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferSingle"
call_parentheses = "Input"

[sort_required]
enabled = true

